-- this script is executed automatically by Spring Boot

CREATE TABLE POST (ID INT PRIMARY KEY auto_increment, TITLE VARCHAR2(100), DESCRIPTION TEXT);

CREATE TABLE ARTICLE (ID INT PRIMARY KEY auto_increment, TITLE VARCHAR2(100), CONTENT TEXT, ORIGINALLINK VARCHAR2(100) NULL);